/********************* Case Study 1  *****************/
SELECT * FROM Fact
SELECT * FROM Product
SELECT * FROM Location



/****** Question 1 **************
 1. Display the number of states present in theLocationTable ***/
SELECT DISTINCT State
FROM Location
ORDER BY State
/* Answer 20 */


/****** Question 2 ************
 2. Howmany products are of regular type?*****/
SELECT COUNT(*) FROM Product WHERE Type = 'Regular'
/* Answer 8 */

/****** Question 3************
3. Howmuch spending has been done on marketing of product ID1?*****/
SELECT SUM(Marketing) AS Marketing_Expense FROM Fact WHERE ProductId = 1
/* Answer 4658 */

/****** Question 4***********
 4. What is the minimum sales of a product?******/
 SELECT * FROM Fact
 SELECT MIN(Sales) AS MinimumSales FROM Fact
 /* Answer 17 */

 /****** Question 5***********
  5. Display the max Cost of Good Sold (COGS).******/

 SELECT MAX(COGS) AS Max_COGS FROM Fact
  /* Answer 364 */


/****** Question 6***********
 6. Display the details of the product where product type is coffee..******/
   SELECT * FROM Product WHERE Product_Type = 'Coffee'

/****** Question 7***********
 7. Display the details where total expenses are greater than40 ******/
SELECT * FROM Fact WHERE Total_Expenses > 40 

/****** Question 8***********
 8. What is the average sales in area code 719? ******/
 SELECT AVG(Sales) From Fact WHERE Area_Code = 719
  /* Answer 186 */

/****** Question 9***********
9. Find out the total profit generated by Colorado state. ******/
SELECT SUM(Profit), State FROM Fact JOIN Location ON Fact.Area_Code = Location.Area_Code WHERE State = 'Colorado' GROUP BY State
  /* Answer 17743 */

/****** Question 10***********
10. Display the average inventory for each product ID. ******/

SELECT AVG(Inventory), Productid FROM Fact GROUP BY ProductiD ORDER BY Productid

/****** Question 11***********
11. Display state in a sequential order in a LocationTable.. ******/
SELECT State FROM Location ORDER BY State ASC


/****** Question 12***********
12. Display the average budget of the Product where the average budget
 margin should be greater than 100. ******/

 SELECT AVG(Budget_Margin, ProductiD FROM Fact GROUP BY ProductiD HAVING AVG(Budget_Margin) > 100

 /****** Question 13***********
13. What is the total sales done on date 2010-01-01?. ******/
SELECT SUM(Sales) FROM Fact WHERE Date = '2010-01-01'

 /****** Question 14***********
14. Display the average total expense of each product ID on anindividual date. ******/

SELECT AVG(Total_Expenses), ProductID, Date FROM Fact GROUP BY ProductID, Date

 /****** Question 15***********
15.  Display the table with the following attributes such as date, productID,
 product_type, product, sales, profit, state, area_code. ******/

 SELECT * FROM Fact
 SELECT * FROM Location
 SELECT * FROM Product


 SELECT F.Date, F.ProductID, P.Product_Type, P.Product, F.Sales, F.Profit, L.State, F.Area_Code FROM Fact AS F
 INNER JOIN Product AS P ON F.ProductID = P.ProductID
 INNER JOIN Location AS L ON F.Area_Code = L.Area_Code


/****** Question 16***********
16.  Display the rank without any gap to show the sales wiserank.. ******/
SELECT DENSE_RANK() OVER (Order by Sales DESC), Sales FROM Fact


/****** Question 17***********
17. Find the state wise profit and sales. ******/
SELECT State, Sum(Profit), SUM(Sales) FROM Fact 
JOIN Location ON Fact.Area_Code = Location.Area_Code GROUP BY State

/********* Question 18 ************
18. Find the state wise profit and sales along with the productname.*********/

SELECT State, Sum(Profit) AS State_Wise_Profit, SUM(Sales) AS Total_Sale, Product FROM Fact 
JOIN Product ON Fact.ProductID = Product.ProductID 
JOIN Location ON Fact.Area_Code = Location.Area_Code 
GROUP BY State, Product

/********** Question 19*********
19. If there is an increase in sales of 5%, calculate the increasedsales **********/
SELECT Sales, Sales*0.05 AS INCREMENT, Sales+(Sales*0.05) AS Updated_Sale_Amount FROM Fact 


/********* Question 20****************
20. Find the maximum profit along with the product ID and producttype.*/
SELECT * FROM Fact
SELECT * FROM Product

SELECT F.ProductID, P.Product_type, MAX(Profit) FROM FACT AS F
JOIN Product AS P ON F.ProductID = P.ProductID
GROUP BY F.ProductID, P.Product_Type


/********* Question 21****************
21. Create a stored procedure to fetch the result according to theproduct type
    from ProductTable..*/

CREATE PROCEDURE Sample_ProductType
@Fetch_Product_Type VARCHAR (20)
AS
SELECT * FROM Product WHERE Product_Type = @Fetch_Product_Type

EXECUTE Sample_ProductType 'Coffee'
EXECUTE Sample_ProductType 'Milk'



/********* Question 22****************
22. Write a query by creating a condition in which if the total expenses isless than
    60 then it is a profit or else loss..*********/
SELECT Total_Expenses, IIF (Total_Expenses < 40, 'Profit', 'Loss')  FROM Fact




/********* Question 23*********************** Having issues with Week function ******************************
23. Give the total weekly sales value with the date and product IDdetails. Use
 roll-up to pull the data in hierarchical order. *******/

SELECT Date, ProductId, YEAR(Date) AS Year, WEEK(Date) AS Week, SUM(Budget_Sales) 
FROM Fact
GROUP BY ROLLUP ( Date, ProductId, YEAR(Date), Week_Name(WEEK.Date))

Datename(Week.Date)


SELECT Continent, Country, City, SUM(SaleAmount)
FROM
Sales
GROUP BY ROLLUP Continent, Country, City

SELECT * FROM Fact
SELECT * FROM Location
SELECT * FROM Product

/********* Question 24****************
24. Apply union and intersection operator on the tables which consistof
    attribute area code. *******/
SELECT Area_Code, State, Market, Market_Size FROM Fact
UNION 
SELECT Area_Code, State, Market, Market_Size FROM Location

SELECT Area_Code FROM Fact
INTERSECT 
SELECT Area_Code FROM Location

/********* Question 25****************
25. Create a user-defined function for the product table to fetch aparticular
 product type based upon the user’s preference.. *******/


CREATE FUNCTION udf_user_Preffered_Product 
(
	@Product VARCHAR (50)
)
RETURNS TABLE
RETURN
(
	SELECT Product_Type FROM Product WHERE Product = @Product
)

SELECT dbo.udf_user_Preffered_Product('Amaretto');

SELECT * FROM dbo.udf_user_Preffered_Product('Amaretto');



/********* Question 26****************
26. Change the product type from coffee to tea where product ID is 1and undo
    it... *******/

BEGIN TRANSACTION
UPDATE Product SET Product_Type = 'Tea' WHERE ProductId = 1

ROLLBACK TRANSACTION


/********* Question 27****************
27. Display the date, product ID and sales where total expenses are
    between 100 to 200.. *******/

SELECT Date, ProductID, Sales
FROM Fact
WHERE Total_Expenses BETWEEN 100 AND 200;



/********* Question 28****************
28. Delete the records in the Product Table for regulartype.. *******/

DELETE FROM Product WHERE Type = 'Regular'

/********* Question 29 ****************
/29. Display the ASCII value of the fifth character from the columnProduct.******/ 

SELECT ASCII(SUBSTRING(Product, 5, 1)) AS FifthASCII
FROM Product;




